### ISSUE TITLE
I have no idea how to install this in A1111.

### ISSUE THREAD

**Issue by VemberRoss** [p1atdev/sd-danbooru-tags-upsampler#20]
I guess that's more of an issue with me than the project, huh? I tried installing it by entering the URL in the Extensions tab, but it didn't work, and I'm not sure how I'm supposed to add it. It seems like a pretty cool extension. I just dunno how to get it running. :(

**Comment by p1atdev** [comment]
Are there any errors displayed in the terminal?

**Comment by VemberRoss** [comment]
This is the error I get when I start A1111 after installing the extension. I tried running the upgrade command it said to use, and it still gives the error, even though if I run the upgrade command again it says all the requirements of the update are "already satisfied." 

> *** Error loading script: dart_upsampler.py
    Traceback (most recent call last):
      File "Q:\SD\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\import_utils.py", line 1086, in _get_module
        return importlib.import_module("." + module_name, self.__name__)
      File "C:\Users\LRoss\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "Q:\SD\stable-diffusion-webui\venv\lib\site-packages\optimum\exporters\onnx\utils.py", line 42, in <module>
        raise ImportError(
    ImportError: We found an older version of diffusers 0.16.1 but we require diffusers to be >= 0.18.0. Please update diffusers by running `pip install --upgrade diffusers`

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "Q:\SD\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\import_utils.py", line 1086, in _get_module
        return importlib.import_module("." + module_name, self.__name__)
      File "C:\Users\LRoss\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "Q:\SD\stable-diffusion-webui\venv\lib\site-packages\optimum\onnxruntime\modeling_decoder.py", line 31, in <module>
        from ..exporters.onnx import MODEL_TYPES_REQUIRING_POSITION_IDS, main_export
      File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
      File "Q:\SD\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\import_utils.py", line 1076, in __getattr__
        module = self._get_module(self._class_to_module[name])
      File "Q:\SD\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\import_utils.py", line 1088, in _get_module
        raise RuntimeError(
    RuntimeError: Failed to import optimum.exporters.onnx.utils because of the following error (look up to see its traceback):
    We found an older version of diffusers 0.16.1 but we require diffusers to be >= 0.18.0. Please update diffusers by running `pip install --upgrade diffusers`

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "Q:\SD\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "Q:\SD\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "Q:\SD\stable-diffusion-webui\extensions\sd-danbooru-tags-upsampler\scripts\dart_upsampler.py", line 16, in <module>
        from dart.generator import DartGenerator
      File "Q:\SD\stable-diffusion-webui\extensions\sd-danbooru-tags-upsampler\dart\generator.py", line 15, in <module>
        from optimum.onnxruntime import ORTModelForCausalLM
      File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
      File "Q:\SD\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\import_utils.py", line 1076, in __getattr__
        module = self._get_module(self._class_to_module[name])
      File "Q:\SD\stable-diffusion-webui\venv\lib\site-packages\transformers\utils\import_utils.py", line 1088, in _get_module
        raise RuntimeError(
    RuntimeError: Failed to import optimum.onnxruntime.modeling_decoder because of the following error (look up to see its traceback):
    Failed to import optimum.exporters.onnx.utils because of the following error (look up to see its traceback):
    We found an older version of diffusers 0.16.1 but we require diffusers to be >= 0.18.0. Please update diffusers by running `pip install --upgrade diffusers`

**Comment by p1atdev** [comment]
Maybe you should activate the webui's venv before using pip.

```bash
Q:\SD\stable-diffusion-webui\venv\Scripts\activate
```

then,

```
pip install --upgrade diffusers
```

**Comment by VemberRoss** [comment]
That worked! Thanks! Sorry I'm dumb!
